/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuya_test_FF1Test */

#ifndef _Included_com_tuya_test_FF1Test
#define _Included_com_tuya_test_FF1Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tuya_test_FF1Test
 * Method:    decrypt
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuya_test_FF1Test_decrypt
        (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
